AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: CUDOS-User
  MyAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref MyIAMUser

  MyIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudFormationPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DescribeStackEvents'
                  - 'cloudformation:DescribeStackResources'
                  - 'cloudformation:DescribeStackResource'
                Resource: '*'
        - PolicyName: QuickSightPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'quicksight:Describe*'
                  - 'quicksight:Get*'
                  - 'quicksight:List*'
                Resource: '*'
Outputs:
  AccessKeyId:
    Value: !Ref MyAccessKey
  SecretAccessKey:
    Value: !GetAtt MyAccessKey.SecretAccessKey
  UserARN:
    Value: !GetAtt MyIAMUser.Arn
  RoleARN:
    Value: !GetAtt MyIAMRole.Arn

 