AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template

Parameters:
  GroupName:
    Type: String
    Description: The group name of the IAM role to be created.

Resources:
  CudosIAMGroupPolicy:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: CudosIAMGroupPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: StateFunctionPermissions
            Effect: Allow
            Action: 
              - states:*
            Resource: '*'

          - Sid: CloudFormationPermissions
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:ListStacks
              - cloudformation:DescribeStackResources
              - cloudformation:ListStackResources
            Resource: "*"

          - Sid: S3Permissions
            Effect: Allow
            Action: 
              - s3:*
            Resource: "*"
          - Sid: DenyDeleteSPermissions
            Effect: Deny
            Action:
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:DeleteBucketPolicy
            Resource: "*"

          - Sid: LambdaPermissions
            Effect: Allow
            Action: 
              - lambda:*
            Resource: "*"
          - Sid: DenyDeleteLambdaPermissions
            Effect: Deny
            Action:
              - lambda:DeleteFunction
              - lambda:DeleteAlias
              - lambda:DeleteEventSourceMapping
            Resource: "*"
      Groups: 
        - !Ref GroupName
