AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template

Parameters:
  GroupName:
    Type: String
    Description: The group name of the IAM role to be created.

Resources:
  CudosIAMGroupPolicy:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: CudosIAMGroupPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: StateFunctionPermissions
            Effect: Allow
            Action: 
              - states:ListStateMachineVersions
              - states:DescribeActivity
              - states:ListStateMachines
              - states:DescribeStateMachine
              - states:ListActivities
              - states:ListExecutions
              - states:DescribeStateMachineAlias
              - states:UntagResource
              - states:ValidateStateMachineDefinition
              - states:TagResource
              - states:DescribeStateMachineForExecution
              - states:ListStateMachineAliases
              - states:RevealSecrets
              - states:DescribeExecution
              - states:GetExecutionHistory
              - states:DescribeMapRun
              - states:ListMapRuns
              - states:CreateStateMachine
              - states:ListTagsForResource
            Resource: '*'
          - Sid: CloudFormationPermissions
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:ListStacks
              - cloudformation:DescribeStackResources
              - cloudformation:ListStackResources
            Resource: "*"
      Groups: 
        - !Ref GroupName
