AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM role with permissions to describe, view, and access details QuickSight dashboards.

Resources:
  QuickSightRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CudosUserRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: quicksight.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QuickSightDashboardViewerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - quicksight:DescribeDashboard
                  - quicksight:ListDashboards
                  - quicksight:DescribeDataSet
                  - quicksight:ListDataSets
                  - quicksight:DescribeAnalysis
                  - quicksight:ListAnalyses
                  - quicksight:DescribeUser
                  - quicksight:ListUserGroups
                  - quicksight:ListUsers
                  - quicksight:DescribeDashboardPermissions
                  - quicksight:DescribeAnalysisPermissions
                Resource: "*"

Outputs:
  QuickSightRoleArn:
    Description: The ARN of the created QuickSight IAM role.
    Value: !GetAtt QuickSightRole.Arn
