AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create CudosStepFunctionPolicy

Resources:
  CudosStepFunctionPolicy:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: CudosStepFunctionPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: 
              - states:ListStateMachineVersions
              - states:DescribeActivity
              - states:ListStateMachines
              - states:DescribeStateMachine
              - states:ListActivities
              - states:ListExecutions
              - states:DescribeStateMachineAlias
              - states:UntagResource
              - states:ValidateStateMachineDefinition
              - states:TagResource
              - states:DescribeStateMachineForExecution
              - states:ListStateMachineAliases
              - states:RevealSecrets
              - states:DescribeExecution
              - states:GetExecutionHistory
              - states:DescribeMapRun
              - states:ListMapRuns
              - states:CreateStateMachine
              - states:ListTagsForResource
            Resource: '*'
