AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Admin IAM user, an IAM user group, and assign the user to the group.

Parameters:
  UserName:
    Type: String
    Description: The name of the IAM user to create.

  GroupName:
    Type: String
    Description: The name of the IAM user group to create.

  RoleName:
    Type: String
    Description: The name of the IAM role to be created.

Resources:
  CudosAdminIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName

  CudosAdminIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "sts:AssumeRole"
      Description: A blank IAM role with no policies attached

  CudosAdminIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  CudosAdminIAMUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref CudosAdminIAMGroup
      Users:
        - !Ref CudosAdminIAMUser

  CudosAdminIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${UserName}-Policy"
      Users:
        - !Ref CudosAdminIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:ListUsers
              - iam:GetUser
              - iam:CreateUser
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:PutRolePolicy
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetUserPolicy
              - iam:GetRolePolicy
              - iam:AttachUserPolicy
              - iam:ListUserPolicies
              - iam:ListAttachedUserPolicies
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PassRole
              - iam:ListRoles
              - iam:GetRole
              - iam:ListPolicies
              - iam:GetPolicy
              - iam:PutUserPolicy
              - iam:ListAccessKeys
              - iam:CreateAccessKey
              - iam:ListAttachedGroupPolicies
            Resource: "*"

          - Effect: Allow
            Action:
              - support:DescribeCases
              - support:CreateCase
            Resource: "*"

          - Effect: Allow
            Action: sts:AssumeRole
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${RoleName}"
          
          - Effect: Allow
            Action:
              - quicksight:*
            Resource: "*"
          - Effect: Deny
            Action:
              - quicksight:Delete*
            Resource: "*"

          - Effect: Allow
            Action:
              - glue:*
            Resource: "*"
          - Effect: Deny
            Action:
              - glue:Delete*
            Resource: "*"

Outputs:
  UserNameOutput:
    Description: The name of the created IAM user.
    Value: !Ref CudosAdminIAMUser

  UserArnOutput:
    Description: The ARN of the created IAM user.
    Value: !GetAtt CudosAdminIAMUser.Arn

  RoleArnOutput:
    Description: The ARN of the created IAM Role.
    Value: !GetAtt CudosAdminIAMRole.Arn
