AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM user with QuickSight Viewer permissions.

Parameters:
  UserName:
    Type: String
    Description: The name of the IAM user to create.

Resources:
  CudosIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  QuickSightViewerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: QuickSightDashboardViewerPolicy
      Users:
        - !Ref CudosIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:GetUser
            Resource: "*"
          - Effect: Allow
            Action:
              - quicksight:DescribeDashboard
              - quicksight:ListDashboards
              - quicksight:DescribeDataSet
              - quicksight:ListDataSets
              - quicksight:DescribeAnalysis
              - quicksight:ListAnalyses
              - quicksight:DescribeUser
              - quicksight:ListUserGroups
              - quicksight:ListUsers
              - quicksight:DescribeDashboardPermissions
              - quicksight:DescribeAnalysisPermissions
              - quicksight:RegisterUser
            Resource: "*"

Outputs:
  CudosIAMUserArn:
    Description: The ARN of the created IAM user.
    Value: !GetAtt CudosIAMUser.Arn
